<?php

/**
 * The harness's composer.json and phpunit.xml: this core from its checkout,
 * each gateway from a checkout under /omnishield/plugins when there is one,
 * from GitHub (branch 1.x) otherwise; every package's tests in one run.
 * Files are rewritten only when they change, so the entrypoint knows when
 * to install.
 */
$plugins = require __DIR__.'/plugins.php';
$core = '/omnishield/core';
$local = '/omnishield/plugins';
$out = '/harness';

$repositories = [['type' => 'path', 'url' => $core, 'options' => ['symlink' => true, 'versions' => ['glitchr/omnishield' => '1.x-dev']]]];
$require = ['glitchr/omnishield' => '1.x-dev'];
$tests = ['Omnishield\\Tests\\' => "$core/Tests/"];
$suites = ['core' => "$core/Tests"];
$gateways = [];
foreach ($plugins as $slug => [$testsNs]) {
    $name = "omnishield/$slug";
    $dir = "$local/$slug";
    $meta = is_file("$dir/composer.json") ? json_decode((string) file_get_contents("$dir/composer.json"), true) : null;
    if (($meta['name'] ?? null) === $name) {
        $repositories[] = ['type' => 'path', 'url' => $dir, 'options' => ['symlink' => true, 'versions' => [$name => '1.x-dev']]];
        $testDir = "$dir/Tests";
        $gateways[$slug] = 'checkout';
    } else {
        // A plain git clone over HTTPS: no GitHub API (anonymous calls are rate limited), no ssh in the image.
        $repositories[] = ['type' => 'git', 'url' => "https://github.com/glitchr-studio/omnishield-$slug.git"];
        $testDir = "$out/vendor/omnishield/$slug/Tests";
        $gateways[$slug] = 'github';
    }
    $require[$name] = '1.x-dev';
    $tests[$testsNs] = $testDir.'/';
    $suites[$slug] = $testDir;
}

$composer = [
    'name' => 'glitchr/omnishield-harness',
    'description' => 'glitchr/omnishield with every gateway: generated by docker/harness/setup.php, do not edit.',
    'type' => 'project',
    'license' => 'MIT',
    'repositories' => $repositories,
    'require' => $require + [
        'php' => '>=8.2',
        'symfony/console' => '^7.0|^8.0',
        'symfony/http-client' => '^7.0|^8.0',
    ],
    'require-dev' => [
        'phpunit/phpunit' => '^11.0',
        'psr/cache' => '^3.0',
        'symfony/cache' => '^7.0|^8.0',
        'symfony/config' => '^7.0|^8.0',
        'symfony/dependency-injection' => '^7.0|^8.0',
        'symfony/form' => '^7.0|^8.0',
        'symfony/http-foundation' => '^7.0|^8.0',
        'symfony/http-kernel' => '^7.0|^8.0',
        'symfony/routing' => '^7.0|^8.0',
        'symfony/translation' => '^7.0|^8.0',
        'symfony/twig-bridge' => '^7.0|^8.0',
        'symfony/validator' => '^7.0|^8.0',
        'symfony/yaml' => '^7.0|^8.0',
        'twig/twig' => '^3.0',
    ],
    'autoload' => ['psr-4' => ['Omnishield\\Harness\\' => "$core/docker/harness/src/"]],
    'autoload-dev' => ['psr-4' => $tests],
    'minimum-stability' => 'dev',
    'prefer-stable' => true,
    'config' => ['sort-packages' => true],
];
$json = json_encode($composer, \JSON_PRETTY_PRINT | \JSON_UNESCAPED_SLASHES)."\n";
if (!is_file("$out/composer.json") || file_get_contents("$out/composer.json") !== $json) {
    file_put_contents("$out/composer.json", $json);
    echo "composer.json composed: ", implode(', ', array_map(static fn ($s, $f) => "$s ($f)", array_keys($gateways), $gateways)), "\n";
}

$xml = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<phpunit xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:noNamespaceSchemaLocation=\"vendor/phpunit/phpunit/phpunit.xsd\" bootstrap=\"vendor/autoload.php\" colors=\"true\" failOnWarning=\"true\" cacheDirectory=\".phpunit.cache\">\n    <testsuites>\n";
foreach ($suites as $suite => $dir) {
    $xml .= "        <testsuite name=\"$suite\"><directory>$dir</directory></testsuite>\n";
}
$xml .= "    </testsuites>\n</phpunit>\n";
if (!is_file("$out/phpunit.xml") || file_get_contents("$out/phpunit.xml") !== $xml) {
    file_put_contents("$out/phpunit.xml", $xml);
}
